[build]
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "RECAPTCHA_SITE_KEY,VITE_RECAPTCHA_SITE_KEY" }

[[redirects]]
  from = "/api/*"
  to = "https://tr-playground-api.onrender.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
